### ISSUE TITLE
github actions

### ISSUE THREAD

**Issue by chenminhua** [chenminhua/dev#12]
https://learning.oreilly.com/library/view/learning-github-actions/9781098131067/ch02.html#idm45717936773808

### Steps
basic unit of execution you deal with

```yml
steps:
- uses: actions/checkout@v3
- name: setup Go version
  uses: actions/setup-go@v3
  with: 
    go-version: '1.18.0'
- run: go run helloworld.go
```

### Runners
vms or containers where the steps are executed. Simply defined via the runs-on: clause
```
runs-on: ubuntu-latest
```

### Jobs
- Jobs aggregate steps and define which runner to execute them on.
- A job is usually targeted towards accomplishing one particular goal of the overall workflow.
```yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
  - uses: actions/checkout@v3
  - name: setup Go version'
    uses: actions/setup-go@v2
    with:
      go-version: '1.14.0'
  - run: go run helloworld.go
```

### workflow 
workflow is a pipeline. It define the type of inputs(events), and the jobs

```yml
name: Simple Go Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go version
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.1'
      - run: go run hello-world.go
```

**Comment by chenminhua** [comment]
### action example
action must have action.yml file

```yml
name: ...
description: ...
inputs:
  repository ...
  ref: ...
  token: ...
  ...
runs: ...
```

### usage
```
- uses: actions/checkout@3
  with:
    repository: ...
    ref: ...
    token: ...
    ...
```
